#!/bin/sh /etc/rc.common

START=55

USE_PROCD=1
PROG=/usr/sbin/wifictld

start_service () {
	procd_open_instance
	[ -e /proc/sys/kernel/core_pattern ] && {
		procd_set_param limits core="unlimited"
	}
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn ${respawn_threshold:-3660} ${respawn_timeout:-5} ${respawn_retry:-0}
	procd_set_param command "$PROG"
	procd_set_param watch network.wireless
	procd_close_instance
}

reload_service () {
	ubus call wifictld rebind > /dev/null
}

service_triggers() {
	local script=$(readlink "$initscript")
	local name=$(basename "${script:-$initscript}")

	procd_open_trigger
	procd_add_raw_trigger "hostapd.*" 0 "/etc/init.d/$name" reload
	procd_close_trigger
}
